# Generated by Django 6.0.4 on 2026-04-28 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('ownership', models.CharField(choices=[('Individual', 'Individual'), ('Joint', 'Joint')], max_length=20)),
                ('govt_id_type', models.CharField(choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN'), ('Voter_ID', 'Voter ID'), ('Passport', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20)),
                ('load_applied', models.IntegerField()),
                ('date_of_application', models.DateField()),
                ('reviewer_id', models.IntegerField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_comments', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
