# Generated by Django 6.0.4 on 2026-04-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='user',
        ),
    ]
