# Generated by Django 6.0.4 on 2026-04-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_remove_connection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='reviewer_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='connection',
            name='reviewer_name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
